export const STATS_LABELS = {
  FEES_EARNED: 'Fees earned',
  YOUR_REBATE_RATE: 'Your Rebate Rate',
  ACTIVE_TRADERS: 'Active traders',
  TRADING_VOLUME: 'Trading Volume',
  NEW_TRADERS: 'New Traders',
  INVITEES: 'Invitees',
} as const;

export const ALL_STATS_LABELS = [
  STATS_LABELS.FEES_EARNED,
  STATS_LABELS.YOUR_REBATE_RATE,
  STATS_LABELS.ACTIVE_TRADERS,
  STATS_LABELS.TRADING_VOLUME,
  STATS_LABELS.NEW_TRADERS,
  STATS_LABELS.INVITEES,
] as const;
