import type { TwapData } from './HistoryTwapTableRow';

export const historyTwapsData: TwapData[] = [
    {
        time: '3/17/2025 - 16:15:33',
        coin: 'BTC',
        totalSize: '0.00817 BTC',
        executedSize: '0.00013 BTC',
        averagePrice: '84,204',
        totalRuntime: '30 minutes',
        reduceOnly: 'No',
        randomize: 'Yes',
        status: 'Terminated',
    },
    {
        time: '3/17/2025 - 16:15:04',
        coin: 'BTC',
        totalSize: '0.00817 BTC',
        executedSize: null,
        averagePrice: null,
        totalRuntime: '30 minutes',
        reduceOnly: 'No',
        randomize: 'Yes',
        status: 'Activated',
    },
    {
        time: '3/5/2025 - 13:12:07',
        coin: 'BTC',
        totalSize: '0.02224 BTC',
        executedSize: '0.02224 BTC',
        averagePrice: '89,267',
        totalRuntime: '5 minutes',
        reduceOnly: 'No',
        randomize: 'No',
        status: 'Finished',
    },
    {
        time: '3/5/2025 - 13:07:05',
        coin: 'BTC',
        totalSize: '0.02224 BTC',
        executedSize: null,
        averagePrice: null,
        totalRuntime: '5 minutes',
        reduceOnly: 'No',
        randomize: 'No',
        status: 'Activated',
    },
];
