// scripts/write-version.js
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

// Get __dirname in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Path to package.json
const packageJsonPath = path.join(__dirname, '../package.json');
const versionJsonPath = path.join(__dirname, '../public/version.json');

// Read and parse package.json
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

const currentDatetime = new Date().toISOString();

// Use the version property from frontend/package.json
const frontendPackageVersionNumber = packageJson.version.split('-')[0];

const useAutoGeneratedVersion =
    process.env.CONTEXT === 'deploy-preview' ||
    process.env.CONTEXT === 'branch-deploy';

const newVersion = {
    version: useAutoGeneratedVersion
        ? currentDatetime
        : frontendPackageVersionNumber,
};

// Check if version file needs updating
function needsVersionUpdate() {
    if (!fs.existsSync(versionJsonPath)) {
        return true;
    }

    try {
        const existingVersion = JSON.parse(
            fs.readFileSync(versionJsonPath, 'utf8'),
        );
        return existingVersion.version !== newVersion.version;
    } catch (e) {
        return true; // If file is corrupted, rewrite it
    }
}

// Write to the public directory so it gets copied to the build output
const outDir = path.join(__dirname, '../public');

if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

if (needsVersionUpdate()) {
    fs.writeFileSync(versionJsonPath, JSON.stringify(newVersion, null, 2));
    console.log(`Version updated: ${newVersion.version}`);
} else {
    console.log('Version file unchanged, skipping write.');
}
