export const positionsData: PositionData[] = [
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: '$0.53 (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
    {
        coin: 'ETH',
        leverageBadge: '10x',
        size: '0.0001 ETH',
        positionValue: '$10.53',
        entryPrice: '2,534.00',
        markPrice: '2,643.00',
        pnl: {
            value: '+$0.02',
            percentage: '+2.6%',
            isPositive: true,
        },
        liqPrice: 'N/A',
        margin: 'Lat one (Cross)',
        funding: '$0.00',
        tpsl: '-- / --',
    },
];
